# Generated by Django 5.1.6 on 2025-02-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name_plural": "Messages"},
        ),
    ]
